baseurl = "https://ventrisco.github.io/"
languageCode = "en-us"
title = "Ventris & Co"
theme = "ghostwriter"
preserveTaxonomyNames = false
paginate = 10
disqusShortname = "ventrisco"
googleAnalytics = "UA-93157727-1"
canonifyurls = "true"

[Author]
    name = "M. Ventris"

[Taxonomies]
    tag = "tags"

[params]
    # Sets the meta tag description, usually reserved for the main page
    headline = "Ventris & Co"
    description = "Hacking Quantitative Finance"
    email = "m@ventris.co"
    github = "https://github.com/ventrisco"


# parms.intro will appear on the sidebar
# This is optional, but it's suggested to use
[params.intro]
    header    = "Ventris & Co"


[Permalinks]
    post = "/:year/:month/:day/:filename/"


